In [1]:
import torch 
import torch.nn as nn 

### Creating Dropout layer from scratch 

In [14]:
class MyDropout(nn.Module):
    def __init__(self, p=0.3):
        super(MyDropout, self).__init__()
        assert 0 < p < 1 
        self.p = p 

    def forward(self, X:torch.Tensor):
        if self.training: #model.train()
            mask = torch.rand_like(X) > self.p 
            X = X * mask / (1 - self.p)
        # in model.eval() it does not works
        return X

In [15]:
dropout_layer = MyDropout(p=0.5)
input_tensor = torch.randn(1, 10)  # Example input tensor with shape (1, 10)
print(output_tensor)
output_tensor = dropout_layer(input_tensor)
print(output_tensor)

tensor([[ 0.0000,  1.5213, -0.0000,  1.3990, -0.0000,  0.1018, -0.0621,  5.6282,
         -0.0000,  0.0000]])
tensor([[False, False,  True, False, False, False,  True,  True, False, False]])
tensor([[-0.0000, -0.0000,  2.5190, -0.0000, -0.0000, -0.0000, -2.1518,  0.5784,
          0.0000, -0.0000]])
